package com.ithinksky.base.model;

import java.io.Serializable;
import java.util.Date;

public class Baseentity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_entity.id
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_entity.create_time
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_entity.create_by
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_entity.update_time
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_entity.update_by
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_entity.remark
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_entity.id
     *
     * @return the value of t_base_entity.id
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_entity.id
     *
     * @param id the value for t_base_entity.id
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_entity.create_time
     *
     * @return the value of t_base_entity.create_time
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_entity.create_time
     *
     * @param createTime the value for t_base_entity.create_time
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_entity.create_by
     *
     * @return the value of t_base_entity.create_by
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_entity.create_by
     *
     * @param createBy the value for t_base_entity.create_by
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_entity.update_time
     *
     * @return the value of t_base_entity.update_time
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_entity.update_time
     *
     * @param updateTime the value for t_base_entity.update_time
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_entity.update_by
     *
     * @return the value of t_base_entity.update_by
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_entity.update_by
     *
     * @param updateBy the value for t_base_entity.update_by
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_entity.remark
     *
     * @return the value of t_base_entity.remark
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_entity.remark
     *
     * @param remark the value for t_base_entity.remark
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public static Baseentity.Builder builder() {
        return new Baseentity.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_base_entity
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        private Baseentity obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_entity
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder() {
            this.obj = new Baseentity();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_entity.id
         *
         * @param id the value for t_base_entity.id
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_entity.create_time
         *
         * @param createTime the value for t_base_entity.create_time
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_entity.create_by
         *
         * @param createBy the value for t_base_entity.create_by
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder createBy(String createBy) {
            obj.setCreateBy(createBy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_entity.update_time
         *
         * @param updateTime the value for t_base_entity.update_time
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder updateTime(Date updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_entity.update_by
         *
         * @param updateBy the value for t_base_entity.update_by
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder updateBy(String updateBy) {
            obj.setUpdateBy(updateBy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_entity.remark
         *
         * @param remark the value for t_base_entity.remark
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder remark(String remark) {
            obj.setRemark(remark);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_entity
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Baseentity build() {
            return this.obj;
        }
    }
}