package com.ithinksky.base.model;

import java.io.Serializable;
import java.util.Date;

/**
        *
        * This class was generated by MyBatis Generator.
        * This class corresponds to the database table sys_dict_data
        *
        * @mbg.generated do_not_delete_during_merge
        * @project https://github.com/itfsw/mybatis-generator-plugin
        */
public class SysDictData implements Serializable {
    /**
     * Database Column Remarks:
     *   字典编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .dict_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Integer dictCode;

    /**
     * Database Column Remarks:
     *   字典排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .dict_sort
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Integer dictSort;

    /**
     * Database Column Remarks:
     *   字典标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .dict_label
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String dictLabel;

    /**
     * Database Column Remarks:
     *   字典键值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .dict_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String dictValue;

    /**
     * Database Column Remarks:
     *   字典类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .dict_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String dictType;

    /**
     * Database Column Remarks:
     *   样式属性（其他样式扩展）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .css_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String cssClass;

    /**
     * Database Column Remarks:
     *   表格回显样式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .list_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String listClass;

    /**
     * Database Column Remarks:
     *   是否默认（0=否，1=是）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .is_default
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Byte isDefault;

    /**
     * Database Column Remarks:
     *   状态（1正常 0停用）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .create_by
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .create_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .update_by
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .update_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data
        .remark
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .dict_code
     *
     * @return the value of sys_dict_data.dict_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .dict_code
     *
     * @param dictCode the value for sys_dict_data
        .dict_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setDictCode(Integer dictCode) {
        this.dictCode = dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .dict_sort
     *
     * @return the value of sys_dict_data.dict_sort
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getDictSort() {
        return dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .dict_sort
     *
     * @param dictSort the value for sys_dict_data
        .dict_sort
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setDictSort(Integer dictSort) {
        this.dictSort = dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .dict_label
     *
     * @return the value of sys_dict_data.dict_label
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getDictLabel() {
        return dictLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .dict_label
     *
     * @param dictLabel the value for sys_dict_data
        .dict_label
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setDictLabel(String dictLabel) {
        this.dictLabel = dictLabel == null ? null : dictLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .dict_value
     *
     * @return the value of sys_dict_data.dict_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .dict_value
     *
     * @param dictValue the value for sys_dict_data
        .dict_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .dict_type
     *
     * @return the value of sys_dict_data.dict_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .dict_type
     *
     * @param dictType the value for sys_dict_data
        .dict_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .css_class
     *
     * @return the value of sys_dict_data.css_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getCssClass() {
        return cssClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .css_class
     *
     * @param cssClass the value for sys_dict_data
        .css_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setCssClass(String cssClass) {
        this.cssClass = cssClass == null ? null : cssClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .list_class
     *
     * @return the value of sys_dict_data.list_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getListClass() {
        return listClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .list_class
     *
     * @param listClass the value for sys_dict_data
        .list_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setListClass(String listClass) {
        this.listClass = listClass == null ? null : listClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .is_default
     *
     * @return the value of sys_dict_data.is_default
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Byte getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .is_default
     *
     * @param isDefault the value for sys_dict_data
        .is_default
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setIsDefault(Byte isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .status
     *
     * @return the value of sys_dict_data.status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .status
     *
     * @param status the value for sys_dict_data
        .status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .create_by
     *
     * @return the value of sys_dict_data.create_by
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .create_by
     *
     * @param createBy the value for sys_dict_data
        .create_by
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .create_time
     *
     * @return the value of sys_dict_data.create_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .create_time
     *
     * @param createTime the value for sys_dict_data
        .create_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .update_by
     *
     * @return the value of sys_dict_data.update_by
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .update_by
     *
     * @param updateBy the value for sys_dict_data
        .update_by
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .update_time
     *
     * @return the value of sys_dict_data.update_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .update_time
     *
     * @param updateTime the value for sys_dict_data
        .update_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data
        .remark
     *
     * @return the value of sys_dict_data.remark
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data
        .remark
     *
     * @param remark the value for sys_dict_data
        .remark
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static SysDictData.Builder builder() {
        return new SysDictData.Builder();
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_dict_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private SysDictData obj;

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table sys_dict_data
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public Builder() {
            this.obj = new SysDictData();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .dict_code
         *
         * @param dictCode the value for sys_dict_data
            .dict_code
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dictCode(Integer dictCode) {
            obj.setDictCode(dictCode);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .dict_sort
         *
         * @param dictSort the value for sys_dict_data
            .dict_sort
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dictSort(Integer dictSort) {
            obj.setDictSort(dictSort);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .dict_label
         *
         * @param dictLabel the value for sys_dict_data
            .dict_label
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dictLabel(String dictLabel) {
            obj.setDictLabel(dictLabel);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .dict_value
         *
         * @param dictValue the value for sys_dict_data
            .dict_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dictValue(String dictValue) {
            obj.setDictValue(dictValue);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .dict_type
         *
         * @param dictType the value for sys_dict_data
            .dict_type
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dictType(String dictType) {
            obj.setDictType(dictType);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .css_class
         *
         * @param cssClass the value for sys_dict_data
            .css_class
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder cssClass(String cssClass) {
            obj.setCssClass(cssClass);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .list_class
         *
         * @param listClass the value for sys_dict_data
            .list_class
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder listClass(String listClass) {
            obj.setListClass(listClass);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .is_default
         *
         * @param isDefault the value for sys_dict_data
            .is_default
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isDefault(Byte isDefault) {
            obj.setIsDefault(isDefault);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .status
         *
         * @param status the value for sys_dict_data
            .status
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder status(Byte status) {
            obj.setStatus(status);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .create_by
         *
         * @param createBy the value for sys_dict_data
            .create_by
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createBy(String createBy) {
            obj.setCreateBy(createBy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .create_time
         *
         * @param createTime the value for sys_dict_data
            .create_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .update_by
         *
         * @param updateBy the value for sys_dict_data
            .update_by
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateBy(String updateBy) {
            obj.setUpdateBy(updateBy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .update_time
         *
         * @param updateTime the value for sys_dict_data
            .update_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(Date updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_data
            .remark
         *
         * @param remark the value for sys_dict_data
            .remark
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder remark(String remark) {
            obj.setRemark(remark);
            return this;
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table sys_dict_data
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public SysDictData build() {
            return this.obj;
        }
    }
}