package com.ithinksky.base.model;

import java.io.Serializable;
import java.util.Date;

public class SysDictData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.dict_code
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private Integer dictCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.dict_sort
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private Integer dictSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.dict_label
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private String dictLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.dict_value
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private String dictValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.css_class
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private String cssClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.list_class
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private String listClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.is_default
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private Byte isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.status
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.create_by
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.create_time
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.update_by
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.update_time
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.remark
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.dict_code
     *
     * @return the value of sys_dict_data.dict_code
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public Integer getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.dict_code
     *
     * @param dictCode the value for sys_dict_data.dict_code
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setDictCode(Integer dictCode) {
        this.dictCode = dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.dict_sort
     *
     * @return the value of sys_dict_data.dict_sort
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public Integer getDictSort() {
        return dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.dict_sort
     *
     * @param dictSort the value for sys_dict_data.dict_sort
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setDictSort(Integer dictSort) {
        this.dictSort = dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.dict_label
     *
     * @return the value of sys_dict_data.dict_label
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public String getDictLabel() {
        return dictLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.dict_label
     *
     * @param dictLabel the value for sys_dict_data.dict_label
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setDictLabel(String dictLabel) {
        this.dictLabel = dictLabel == null ? null : dictLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.dict_value
     *
     * @return the value of sys_dict_data.dict_value
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.dict_value
     *
     * @param dictValue the value for sys_dict_data.dict_value
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.dict_type
     *
     * @return the value of sys_dict_data.dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.dict_type
     *
     * @param dictType the value for sys_dict_data.dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.css_class
     *
     * @return the value of sys_dict_data.css_class
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public String getCssClass() {
        return cssClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.css_class
     *
     * @param cssClass the value for sys_dict_data.css_class
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setCssClass(String cssClass) {
        this.cssClass = cssClass == null ? null : cssClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.list_class
     *
     * @return the value of sys_dict_data.list_class
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public String getListClass() {
        return listClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.list_class
     *
     * @param listClass the value for sys_dict_data.list_class
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setListClass(String listClass) {
        this.listClass = listClass == null ? null : listClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.is_default
     *
     * @return the value of sys_dict_data.is_default
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public Byte getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.is_default
     *
     * @param isDefault the value for sys_dict_data.is_default
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setIsDefault(Byte isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.status
     *
     * @return the value of sys_dict_data.status
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.status
     *
     * @param status the value for sys_dict_data.status
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.create_by
     *
     * @return the value of sys_dict_data.create_by
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.create_by
     *
     * @param createBy the value for sys_dict_data.create_by
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.create_time
     *
     * @return the value of sys_dict_data.create_time
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.create_time
     *
     * @param createTime the value for sys_dict_data.create_time
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.update_by
     *
     * @return the value of sys_dict_data.update_by
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.update_by
     *
     * @param updateBy the value for sys_dict_data.update_by
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.update_time
     *
     * @return the value of sys_dict_data.update_time
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.update_time
     *
     * @param updateTime the value for sys_dict_data.update_time
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.remark
     *
     * @return the value of sys_dict_data.remark
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.remark
     *
     * @param remark the value for sys_dict_data.remark
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysDictData other = (SysDictData) that;
        return (this.getDictCode() == null ? other.getDictCode() == null : this.getDictCode().equals(other.getDictCode()))
            && (this.getDictSort() == null ? other.getDictSort() == null : this.getDictSort().equals(other.getDictSort()))
            && (this.getDictLabel() == null ? other.getDictLabel() == null : this.getDictLabel().equals(other.getDictLabel()))
            && (this.getDictValue() == null ? other.getDictValue() == null : this.getDictValue().equals(other.getDictValue()))
            && (this.getDictType() == null ? other.getDictType() == null : this.getDictType().equals(other.getDictType()))
            && (this.getCssClass() == null ? other.getCssClass() == null : this.getCssClass().equals(other.getCssClass()))
            && (this.getListClass() == null ? other.getListClass() == null : this.getListClass().equals(other.getListClass()))
            && (this.getIsDefault() == null ? other.getIsDefault() == null : this.getIsDefault().equals(other.getIsDefault()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDictCode() == null) ? 0 : getDictCode().hashCode());
        result = prime * result + ((getDictSort() == null) ? 0 : getDictSort().hashCode());
        result = prime * result + ((getDictLabel() == null) ? 0 : getDictLabel().hashCode());
        result = prime * result + ((getDictValue() == null) ? 0 : getDictValue().hashCode());
        result = prime * result + ((getDictType() == null) ? 0 : getDictType().hashCode());
        result = prime * result + ((getCssClass() == null) ? 0 : getCssClass().hashCode());
        result = prime * result + ((getListClass() == null) ? 0 : getListClass().hashCode());
        result = prime * result + ((getIsDefault() == null) ? 0 : getIsDefault().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dictCode=").append(dictCode);
        sb.append(", dictSort=").append(dictSort);
        sb.append(", dictLabel=").append(dictLabel);
        sb.append(", dictValue=").append(dictValue);
        sb.append(", dictType=").append(dictType);
        sb.append(", cssClass=").append(cssClass);
        sb.append(", listClass=").append(listClass);
        sb.append(", isDefault=").append(isDefault);
        sb.append(", status=").append(status);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}