package com.ithinksky.base.model;

import java.io.Serializable;
import java.util.Date;

/**
        *
        * This class was generated by MyBatis Generator.
        * This class corresponds to the database table sys_dict_type
        *
        * @mbg.generated do_not_delete_during_merge
        * @project https://github.com/itfsw/mybatis-generator-plugin
        */
public class SysDictType implements Serializable {
    /**
     * Database Column Remarks:
     *   字典主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type
        .dict_id
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Integer dictId;

    /**
     * Database Column Remarks:
     *   字典名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type
        .dict_name
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String dictName;

    /**
     * Database Column Remarks:
     *   字典类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type
        .dict_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String dictType;

    /**
     * Database Column Remarks:
     *   注释[success(0):成功, fail(1):失败]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type
        .status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type
        .create_by
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type
        .create_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type
        .update_by
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type
        .update_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type
        .remark
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type
        .dict_id
     *
     * @return the value of sys_dict_type.dict_id
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type
        .dict_id
     *
     * @param dictId the value for sys_dict_type
        .dict_id
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setDictId(Integer dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type
        .dict_name
     *
     * @return the value of sys_dict_type.dict_name
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type
        .dict_name
     *
     * @param dictName the value for sys_dict_type
        .dict_name
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type
        .dict_type
     *
     * @return the value of sys_dict_type.dict_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type
        .dict_type
     *
     * @param dictType the value for sys_dict_type
        .dict_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type
        .status
     *
     * @return the value of sys_dict_type.status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type
        .status
     *
     * @param status the value for sys_dict_type
        .status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type
        .create_by
     *
     * @return the value of sys_dict_type.create_by
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type
        .create_by
     *
     * @param createBy the value for sys_dict_type
        .create_by
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type
        .create_time
     *
     * @return the value of sys_dict_type.create_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type
        .create_time
     *
     * @param createTime the value for sys_dict_type
        .create_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type
        .update_by
     *
     * @return the value of sys_dict_type.update_by
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type
        .update_by
     *
     * @param updateBy the value for sys_dict_type
        .update_by
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type
        .update_time
     *
     * @return the value of sys_dict_type.update_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type
        .update_time
     *
     * @param updateTime the value for sys_dict_type
        .update_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type
        .remark
     *
     * @return the value of sys_dict_type.remark
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type
        .remark
     *
     * @param remark the value for sys_dict_type
        .remark
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static SysDictType.Builder builder() {
        return new SysDictType.Builder();
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_dict_type
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private SysDictType obj;

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table sys_dict_type
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public Builder() {
            this.obj = new SysDictType();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_type
            .dict_id
         *
         * @param dictId the value for sys_dict_type
            .dict_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dictId(Integer dictId) {
            obj.setDictId(dictId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_type
            .dict_name
         *
         * @param dictName the value for sys_dict_type
            .dict_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dictName(String dictName) {
            obj.setDictName(dictName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_type
            .dict_type
         *
         * @param dictType the value for sys_dict_type
            .dict_type
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dictType(String dictType) {
            obj.setDictType(dictType);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_type
            .status
         *
         * @param status the value for sys_dict_type
            .status
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder status(Byte status) {
            obj.setStatus(status);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_type
            .create_by
         *
         * @param createBy the value for sys_dict_type
            .create_by
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createBy(String createBy) {
            obj.setCreateBy(createBy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_type
            .create_time
         *
         * @param createTime the value for sys_dict_type
            .create_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_type
            .update_by
         *
         * @param updateBy the value for sys_dict_type
            .update_by
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateBy(String updateBy) {
            obj.setUpdateBy(updateBy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_type
            .update_time
         *
         * @param updateTime the value for sys_dict_type
            .update_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(Date updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_dict_type
            .remark
         *
         * @param remark the value for sys_dict_type
            .remark
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder remark(String remark) {
            obj.setRemark(remark);
            return this;
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table sys_dict_type
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public SysDictType build() {
            return this.obj;
        }
    }

    /**
            * This enum was generated by MyBatis Generator.
            * This enum corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public enum Status {
        SUCCESS(new Byte("0"), "成功"),
        FAIL(new Byte("1"), "失败");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_dict_type
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final Byte value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_dict_type
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String name;

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table sys_dict_type
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        Status(Byte value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table sys_dict_type
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public Byte getValue() {
            return this.value;
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table sys_dict_type
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public Byte value() {
            return this.value;
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table sys_dict_type
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public String getName() {
            return this.name;
        }
    }
}