package com.ithinksky.base.model;

import java.io.Serializable;
import java.util.Date;

public class Systemconfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.config_id
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private Integer configId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.config_name
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private String configName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.config_key
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private String configKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.config_value
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private String configValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.config_type
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private String configType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.create_by
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.create_time
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.update_by
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.update_time
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.remark
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.config_id
     *
     * @return the value of t_system_config.config_id
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public Integer getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.config_id
     *
     * @param configId the value for t_system_config.config_id
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setConfigId(Integer configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.config_name
     *
     * @return the value of t_system_config.config_name
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.config_name
     *
     * @param configName the value for t_system_config.config_name
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.config_key
     *
     * @return the value of t_system_config.config_key
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.config_key
     *
     * @param configKey the value for t_system_config.config_key
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.config_value
     *
     * @return the value of t_system_config.config_value
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.config_value
     *
     * @param configValue the value for t_system_config.config_value
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.config_type
     *
     * @return the value of t_system_config.config_type
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public String getConfigType() {
        return configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.config_type
     *
     * @param configType the value for t_system_config.config_type
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setConfigType(String configType) {
        this.configType = configType == null ? null : configType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.create_by
     *
     * @return the value of t_system_config.create_by
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.create_by
     *
     * @param createBy the value for t_system_config.create_by
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.create_time
     *
     * @return the value of t_system_config.create_time
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.create_time
     *
     * @param createTime the value for t_system_config.create_time
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.update_by
     *
     * @return the value of t_system_config.update_by
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.update_by
     *
     * @param updateBy the value for t_system_config.update_by
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.update_time
     *
     * @return the value of t_system_config.update_time
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.update_time
     *
     * @param updateTime the value for t_system_config.update_time
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.remark
     *
     * @return the value of t_system_config.remark
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.remark
     *
     * @param remark the value for t_system_config.remark
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public static Systemconfig.Builder builder() {
        return new Systemconfig.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_system_config
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        private Systemconfig obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_system_config
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder() {
            this.obj = new Systemconfig();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_system_config.config_id
         *
         * @param configId the value for t_system_config.config_id
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder configId(Integer configId) {
            obj.setConfigId(configId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_system_config.config_name
         *
         * @param configName the value for t_system_config.config_name
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder configName(String configName) {
            obj.setConfigName(configName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_system_config.config_key
         *
         * @param configKey the value for t_system_config.config_key
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder configKey(String configKey) {
            obj.setConfigKey(configKey);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_system_config.config_value
         *
         * @param configValue the value for t_system_config.config_value
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder configValue(String configValue) {
            obj.setConfigValue(configValue);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_system_config.config_type
         *
         * @param configType the value for t_system_config.config_type
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder configType(String configType) {
            obj.setConfigType(configType);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_system_config.create_by
         *
         * @param createBy the value for t_system_config.create_by
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder createBy(String createBy) {
            obj.setCreateBy(createBy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_system_config.create_time
         *
         * @param createTime the value for t_system_config.create_time
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_system_config.update_by
         *
         * @param updateBy the value for t_system_config.update_by
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder updateBy(String updateBy) {
            obj.setUpdateBy(updateBy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_system_config.update_time
         *
         * @param updateTime the value for t_system_config.update_time
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder updateTime(Date updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_system_config.remark
         *
         * @param remark the value for t_system_config.remark
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Builder remark(String remark) {
            obj.setRemark(remark);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_system_config
         *
         * @mbg.generated Tue Jun 30 12:02:59 CST 2020
         */
        public Systemconfig build() {
            return this.obj;
        }
    }
}