package com.ithinksky.base.dao;

import com.ithinksky.base.model.Baseentity;
import com.ithinksky.base.model.BaseentityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    long countByExample(BaseentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int deleteByExample(BaseentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int insert(Baseentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int insertSelective(Baseentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    List<Baseentity> selectByExample(BaseentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    Baseentity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") Baseentity record, @Param("example") BaseentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int updateByExample(@Param("record") Baseentity record, @Param("example") BaseentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int updateByPrimaryKeySelective(Baseentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_entity
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int updateByPrimaryKey(Baseentity record);
}