package com.ithinksky.base.dao;

import com.ithinksky.base.model.SysDictData;
import com.ithinksky.base.model.SysDictDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDictDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    long countByExample(SysDictDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int deleteByExample(SysDictDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int deleteByPrimaryKey(Integer dictCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int insert(SysDictData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int insertSelective(SysDictData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    List<SysDictData> selectByExample(SysDictDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    SysDictData selectByPrimaryKey(Integer dictCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysDictData record, @Param("example") SysDictDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int updateByExample(@Param("record") SysDictData record, @Param("example") SysDictDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int updateByPrimaryKeySelective(SysDictData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int updateByPrimaryKey(SysDictData record);
}