package com.ithinksky.base.dao;

import com.ithinksky.base.model.SysDictData;
import com.ithinksky.base.model.SysDictDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDictDataMapper {
    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    long countByExample(SysDictDataExample example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByExample(SysDictDataExample example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByPrimaryKey(Integer dictCode);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insert(SysDictData record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insertSelective(SysDictData record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    List<SysDictData> selectByExample(SysDictDataExample example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    SysDictData selectByPrimaryKey(Integer dictCode);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExampleSelective(@Param("record") SysDictData record, @Param("example") SysDictDataExample example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExample(@Param("record") SysDictData record, @Param("example") SysDictDataExample example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKeySelective(SysDictData record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_data
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKey(SysDictData record);
}