package com.ithinksky.base.dao;

import com.ithinksky.base.model.SysDictType;
import com.ithinksky.base.model.SysDictTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDictTypeMapper {
    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    long countByExample(SysDictTypeExample example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByExample(SysDictTypeExample example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByPrimaryKey(Integer dictId);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insert(SysDictType record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insertSelective(SysDictType record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    List<SysDictType> selectByExample(SysDictTypeExample example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    SysDictType selectByPrimaryKey(Integer dictId);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExampleSelective(@Param("record") SysDictType record, @Param("example") SysDictTypeExample example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExample(@Param("record") SysDictType record, @Param("example") SysDictTypeExample example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKeySelective(SysDictType record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table sys_dict_type
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKey(SysDictType record);
}