package com.ithinksky.base.dao;

import com.ithinksky.base.model.SysDictType;
import com.ithinksky.base.model.SysDictTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDictTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    long countByExample(SysDictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int deleteByExample(SysDictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int deleteByPrimaryKey(Integer dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int insert(SysDictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int insertSelective(SysDictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    List<SysDictType> selectByExample(SysDictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    SysDictType selectByPrimaryKey(Integer dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysDictType record, @Param("example") SysDictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int updateByExample(@Param("record") SysDictType record, @Param("example") SysDictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int updateByPrimaryKeySelective(SysDictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_type
     *
     * @mbg.generated Fri May 24 11:53:51 CST 2019
     */
    int updateByPrimaryKey(SysDictType record);
}