package com.ithinksky.base.dao;

import com.ithinksky.base.model.Systemconfig;
import com.ithinksky.base.model.SystemconfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemconfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    long countByExample(SystemconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int deleteByExample(SystemconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int deleteByPrimaryKey(Integer configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int insert(Systemconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int insertSelective(Systemconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    List<Systemconfig> selectByExample(SystemconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    Systemconfig selectByPrimaryKey(Integer configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") Systemconfig record, @Param("example") SystemconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int updateByExample(@Param("record") Systemconfig record, @Param("example") SystemconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int updateByPrimaryKeySelective(Systemconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbg.generated Tue Jun 30 12:02:59 CST 2020
     */
    int updateByPrimaryKey(Systemconfig record);
}